ForgetTheMilk/ForgetTheMilk/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Text.RegularExpressions;

namespace ForgetTheMilk.Controllers
{
    public class TaskController : Controller
    {
        public ActionResult Index()
        {
            return View(Tasks);
        }

        public static readonly List<Task> Tasks = new List<Task>();

        [HttpPost]
        public ActionResult Add(string task)
        {
            var taskItem = new Task(task, DateTime.Today, new LinkValidator());
            Tasks.Add(taskItem);
            return RedirectToAction("Index");
        }
    }

    public class Task
    {
        public Task(string task, DateTime today, ILinkValidator linkValidator = null)
        {
            Description = task;
            var dueDatePattern = new Regex(@"(jaan|veebr|märts|apr|mai|juuni|juuli|aug|sept|okt|nov|dets)\s(\d+)");
            var hasDueDate = dueDatePattern.IsMatch(task);
            if (hasDueDate)
            {
                var dueDate = dueDatePattern.Match(task);
                var monthInput = dueDate.Groups[1].Value;
                var month = DateTime.ParseExact(monthInput, "MMM", CultureInfo.CurrentCulture).Month;
                var day = Convert.ToInt32(dueDate.Groups[2].Value);
                var year = today.Year;
                var shouldWrapYear = month < today.Month || (month == today.Month && day < today.Day);
                if (shouldWrapYear)
                {
                    year++;
                }
                if (day <= DateTime.DaysInMonth(year, month))
                {
                    DueDate = new DateTime(year, month, day);
                }
            }

            var linkPattern = new Regex(@"(http://[^\s]+)");
            var hasLink = linkPattern.IsMatch(task);
            if(hasLink)
            {
                var link = linkPattern.Match(task);
                Link = link.Groups[1].Value;
            }



        }
        public string Description { get; set; }
        public string Link { get; set; }
        public DateTime? DueDate { get; set; }
    }
}

ForgetTheMilk/ForgetTheMilk/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Forget The Milk</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Forget The Milk", "Index", "Task", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Tasks", "Index", "Task")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ForgetTheMilk/ForgetTheMilk/Views/Task/Index.cshtml
@model List<ForgetTheMilk.Controllers.Task>

@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <p>Add a task:</p>
    <form action="@Url.Action("Add")" method="POST">
        <input type="text" class="input-lg col-xs-12" name="task" autofocus />
    </form>
</div>

<h3>@Model.Count() Task(s)</h3>
<table class="table">
    <tr>
        <th>Description</th>
        <th>Due Date</th>
        <th>Link</th>
    </tr>
    <tbody>
        @foreach (var task in Model)
        {
            <tr>
                <td>
                    @task.Description
                </td>
                <td>
                    @(task.DueDate.HasValue ? @task.DueDate.Value.ToShortDateString() : "")
                </td>
                <td>
                    <a href="@task.Link">@task.Link</a>
                </td>
            </tr>
        }
    </tbody>
</table>