AspNetCore/AspNetCore/Models/Student.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetCore.Models
{
    public class Student
    {   [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Eesnimi on kohustulik")]
        [StringLength(10, MinimumLength = 5, ErrorMessage = "Eesnime pikkus peab olema 5 ja 10 vahel")]
        [Display(Name = "First name")]
        public string FirstName { get; set; }
        public string LastName { get; set; }
        [Range(1, 35, ErrorMessage = "Vanus peab olema 1 ja 35 vahel")]
        public int? Age { get; set; }

        [Display(Name = "Is Married")]
        public bool? IsMarried { get; set; }

        [Display(Name = "Is Blind")]
        public bool IsBlind { get; set; }
        public List<Loan> Loans { get; set; }

        [NotMapped] // Attribute 
        public string FullName
        {
            get
            {
                return FirstName + " " + LastName;
            }
        }

        public Guid UserId { get; set; }
        public ApplicationUser User { get; set; }

        public byte[]  Picture { get; set; }

        public virtual ICollection<StudentTeacher> StudentTeachers { get; set; }


    }
}

AspNetCore/AspNetCore/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AspNetCore.Data;
using AspNetCore.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace AspNetCore.Controllers
{
    public class StudentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        // Context on otsene viide andmebaasile AspNet
        public StudentsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Students
        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var users = _userManager.Users.Where(x => x.FirstName != "Kalle").ToList();
                users = _context.Users.Where(x => x.FirstName != "Kalle").ToList();

                // Kasutajanime lauri@mail.ee
                ViewData["Name"] = User.Identity.Name;
                string userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            }

            // Sel hetkel, kui ma käivitan .ToList()
            // Tehakse tegelikult päring andmebaasi
            // SELECT * FROM Student

            var students = _context.Student
                .Include(x => x.Loans)
                .ThenInclude(x => x.LoanType)
                .OrderBy(x => x.LastName)
                .ThenBy(x => x.FirstName)
                .ToList();


            return View(students);
        }

        // GET: Students/Details/5
        [Authorize(Roles = "Admin,HR")]
        public async Task<IActionResult> Details(int? id)
        {
            

            if (id == null)
            {  
                return NotFound();
            }

            var student = await _context.Student
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create

        public IActionResult Create()
        {
            if(User.IsInRole("Admin"))
            {
                return View();
            }

            if (User.IsInRole("HR"))
            {
                return RedirectToAction("Index");
            }
            return Content("Ainult admin saab õpilasi lisada");
           
        }

        // POST: Students/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Age,IsMarried")] Student student)
        {
            if (ModelState.IsValid)
            {
                // Add meetod on uue rea lisamiseks tabelisse
                // INSERT INTO Student
                // (FirstName,LastName,Age)
                // VALUES
                // ('student.FirstName', 'student.LastName', Student.Age)
                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> AddStudent([Bind("Id,FirstName,LastName,Age,IsMarried")] Student student)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(student);
                    await _context.SaveChangesAsync();
                }
                catch (Exception)
                {
                    return StatusCode(500, "Sql serveri viga");
                }
              
                return Json(student);
            }
            return StatusCode(500, "Mudeli väärtuste viga");
        }

        public IActionResult HelloName(string name, int count)
        {
            string text = "";

            for (int i = 0; i < count; i++)
            {
                text += "Hello " + name + Environment.NewLine;
            }
            return Content(text);
        }
        
        public IActionResult GetImageFile(int studentId)
        {
            var student = _context.Student.Find(studentId);
            if(student.Picture == null)
            {
                return Content("Pilti pole");
            }
            return File(student.Picture, "image/jpg");
        }

        public IActionResult SumLoans()
        {
            return Content(Convert.ToString(_context.Loan.Sum(x => x.Amount)));
        }


        // GET: Students/Edit/5

        // int?  tähendab, et see on int tüüp, mis lisaks võib olla ka null
        // Nullable
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                // 404 errori lehe näitamine
                return NotFound();
            }
            // Find on nagu FirstOrDefault, aga otsib ainult Primary Key järgi
            // Meil on alati Primary Key Id
            //_context.Student.FirstOrDefault(x => x.Id = id);
            Student student = _context.Student.Find(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //Bind määrab ära propertied, mis tulevad sellesse meetodisse kaasa
        //ülejäänud ignoreeritakse
        public IActionResult Edit(int id, [Bind("Id,FirstName,LastName,Age,IsMarried,IsBlind")] Student student, IFormFile picture)
        {
            if (id != student.Id)
            {
                return NotFound();
            }
            // Kontroll, kas kõik väljad valideerusid
            if (ModelState.IsValid)
            {
                try
                {
                    // Otsi vormis salvestatud Eesnime ja Perekonnanimega kasutaja, ekke id ei ole sama, mis
                    // muudetaval kasutajal ( Kas on olemas teine kasutaja sama ees ja perekonnanimega
                    var existingStudent = _context.Student.Where(x => x.FirstName == student.FirstName
                    && x.LastName == student.LastName && x.Id != student.Id).FirstOrDefault();

                    if (existingStudent != null) 
                    {
                        ModelState.AddModelError("", "Sama nimega kasutaja on juba olemas");
                        return View(student);
                    }
                    // UPDATE Student
                    // SET Firstname = student.FirstName,
                    //      LastName = student.LastName
                    //      Age = student.Age
                    //      .............................
                    // WHERE
                    //      Id = student.Id
                    // Kui Primary Key student.Id = 0
                    // siis tegelikult tehakse hoopis INSERT
                    // Update ei kirjuta veel andmebaasi. Kirjutatakse alles siis, kui kutsun välja
                    // SaveChangesAsync()

                    // Faili üleslaetud pildi salvestamine
                    //FileStream stream = new FileStream("Pictures/" + student.Id + ".jpg", FileMode.Create, FileAccess.Write);
                    //picture.CopyTo(stream);
                    //stream.Close();
                    //MemoryStream stream = new MemoryStream();
                    //picture.CopyTo(stream);

                    //student.Picture = stream.ToArray();
                    //stream.Close();

                    _context.Update(student);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        // Viska uuesti see sama exception, 
                        // mis sa kinni püüdsid
                        throw;
                    }
                }

                // Suunab edasi kindla Actionini
                // nameof(Index) annab mulle stringina Index actioni nime
                // ehk siis tagasta "Index"
                return RedirectToAction(nameof(Index));
            }
            // Võta seesama student objekt (uute andmetega) ja täida 
            // sama view uuesti samade andmetega
            // Lisaks tulevad siia valideerimise veateated
            return View(student);
        }



        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var student = await _context.Student.FindAsync(id);
            _context.Student.Remove(student);
            await _context.SaveChangesAsync();

AspNetCore/AspNetCore/Views/Students/Create.cshtml
@model AspNetCore.Models.Student

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

AspNetCore/AspNetCore/Views/Students/Delete.cshtml
@model AspNetCore.Models.Student

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AspNetCore/AspNetCore/Views/Students/Details.cshtml
@model AspNetCore.Models.Student

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AspNetCore/AspNetCore/Views/Students/Edit.cshtml
@model AspNetCore.Models.Student

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Student</h4>
<hr />

@if(Model.Picture != null)
{
    <img src=@Url.Action("GetImageFile", "Students", new { studentId = Model.Id }) height="100" />
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*
        asp-for annab mulle antud mudeli mingi väärtuse
            antud juhtul Id väärtuse
            *@
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                @*
            asp-for="FirstName" Anna mulle välja FirstName nimetus
                *@
                <label asp-for="FirstName" class="control-label"></label>
                @*
            <input type="text" id="FirstName"
               name="FirstName" value="Aadu" />
                *@
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsMarried" class="control-label"></label>
                @*<input asp-for="IsMarried" class="form-control" />*@
                @*
            @Html.EditorFor(model => model.IsMarried)
            on sama mis
            <input asp-for="IsMarried" class="form-control" />
                *@
                @Html.EditorFor(model => model.IsMarried)
                <span asp-validation-for="IsMarried" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsBlind" class="control-label"></label>
                <input asp-for="IsBlind" />
                <span asp-validation-for="IsBlind" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Picture" class="control-label"></label>
                <input type="file" name="Picture" id="Picture" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

AspNetCore/AspNetCore/Views/Students/Index.cshtml
@*
    Strongly typed view
    Siia viewsse saan ma ainult panna kaasa @model taga kirjeldatud tüüpi objekti
*@
@model IEnumerable<AspNetCore.Models.Student>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>



@ViewData["Name"]
<p>
    <a href="http://www.delfi.ee">DELFI</a>
    <br />
    @* Tag Helpers
        Tee mulle link, mis suunab Create Actionisse
        Kui pole eraldi määratud, siis võetakse sama kontrolleri
        Action, kus me viibime
        asp-action ütleb actioni
        asp-controller ütleb kontrolleri
    *@
    <a asp-action="Create" asp-controller="Students" id="createLink">Create New</a>
    <br />
    @Html.ActionLink("Create New", "Create", "Students")
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @* HTML Helpers
            DisplayNameFor annab mulle mudeli mingi konkreetse
            välja ehk klassi property nimetuse
             "FirstName"
                *@
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>First Loan Description</th>
            <th></th>
        </tr>
    </thead>
    <tbody id="studentsTableBody">
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @* Html.DisplayFor annab mulle välja väärtuse *@
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>

            <td>
                @if(item.Loans != null && item.Loans.Count > 0)
                {
                    @item.Loans[0].LoanType.Description;
                }

            </td>
            <td>
                @* asp-route-id ütleb siis et Edit action pane kaasa parameeter id
            ehk siis peale teist kaldkriipsu kolmas parameeter
            /Students/Edit/4
                *@
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                @{
                    var id = "link_" + item.Id; // link_1 link_2
                }
                <a href="" id='@id' class='linkDeleteStudent'>Delete</a>
            </td>
        </tr>
                        }
    </tbody>
</table>

<input type="button" value="Sum loans" id="buttonSum" />
<input type="button" value="Add Student" id="buttonAddStudent" />
<div id="result"></div>

@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#buttonSum').click(function() {
                $.ajax({
                    type: 'GET',
                    url: '/Students/SumLoans',
                    success: function (result) {
                        // Tavaline javascript sama asja tegemiseks
                        //document.getElementById("result").innerHTML = result;
                        $('#result').html(result);
                        $('#createLink').html("Lisa uus kasutaja");
                        // Anna mulle kõik <a> tagid ehk kõik lingid
                        $('a').html("Lisa");
                      
                    }
                });
            });

            $('#buttonAddStudent').click(function () {
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("AddStudent")', // /Students/AddStudent
                    data: {
                        firstName: "Peeter",
                        lastName: "Paan",
                        age: 20,
                        isMarried: "true",
                    },
                    success: function (result) {
                        var tr = "<tr>";
                        tr += "<td>" + result.id + "</td>";
                        tr += "<td>" + result.firstName + "</td>";
                        tr += "<td>" + result.lastName + "</td>";
                        tr += "<td>" + result.age + "</td>";
                        tr += "<td>";
                        tr += "<a href = '/Students/Edit/" + result.id + "'> Edit</a> | ";
                        tr += "<a href = '/Students/Details/" + result.id + "'>Details</a> | ";
                        tr += "<a href='' id='link_" + result.id + "' class='linkDeleteStudent'>Delete</a>";
                        tr += "</td>";
                        tr += "</tr>";

                        $('#studentsTableBody')
                            .append(tr);
                    },
                    error: function (xhr, status, error) {
                        $('#result').html(xhr.responseText);
                    }
                });
            });

            //$('.linkDeleteStudent').click(function () {
            $(document).on('click', '.linkDeleteStudent', function (event) {
                // preventDefault() lülitab välja lingi sisseehitatud funktsionaalsuse
                // ehk siis antud juhul lingi aadressi "" avamise ehk sama lehe refreshi
                event.preventDefault();

                // this tähendab seda sama elmenti (link), millel ma klikin
                // küsin mis on selle konkreetse lingi id, millele ma klikkisin
                var id = this.id;
                $.ajax({

                    type: 'POST',
                    url: '@Url.Action("DeleteStudent")', // /Students/AddStudent
                    data: {
                        id : id.replace("link_", "")
                    },
                    success: function (result) {
                        $('#link_' + result).parent().parent().remove();
                    }
                });
            });
        });
           
        //});
    </script>
}